language: node_js
node_js: 2.0.0
sudo: false
cache:
    bundler: true
    directories:
    - node_modules
before_script:
  - gem install compass
  - npm install -g gulp bower
  - npm install
  - bower install
  - git config --global user.email "marvin@nebo15.com"
  - git config --global user.name "Marvin The Bot"
script:
  - gulp build --view --production
  - gulp deploy
