var lang = {
    card_exp_date_required: "Expiration date is required",
    card_exp_date_expired: "Wrong expiration date",
    card_wrong_length: "Wrong card length",
    card_wrong_number: "Invalid card number",
    card_number_required: "Card number is required",
    card_number_length_rule: "Card number should be between {0} and {1} numeric characters",
    card_number_length_rule_exact: "Card number should consist of {0} numeric characters",
    card_number_minlength: "Card number should consist at least {0} characters",
    card_number_maxlength: "Card number should consist no more than {0} characters",
    card_cvv2_required: "Code is required",
    card_cvv2_length: "Invalid code",
    card_holder_required: "Card holder name is required",
    card_holder_minlength: "Should contain at least 3 letters",
    street_address_required: "Street address is required",
    street_address_latin: "Enter the address in Latin",
    city_address_required: "City is required",
    city_address_latin: "Enter the city in Latin",
    country_required: "Country is required",
    state_required: "State/province is required",
    state_latin: "Enter the State/Province in Latin",
    zip_required: "ZIP is required",
    email_required: "Email is required",
    email_wrong: "Wrong email format",
    phone_required: "Phone is required",
    phone_wrong: "Wrong phone format",
    wrong_phone: "Phone number should be in the international format (ITU-T E.164)"

};